import type Database from "better-sqlite3";
import { CURRENT_SCHEMA_VERSION } from "../schema-version.js";

export const CURRENT_RACKPAD_SCHEMA_COLUMNS = {
  appSettings: ["key", "value", "updatedAt"],
  auditLog: [
    "id",
    "ts",
    "user",
    "action",
    "entityType",
    "entityId",
    "summary",
  ],
  deviceImages: [
    "id",
    "deviceId",
    "label",
    "fileName",
    "mimeType",
    "dataUrl",
    "notes",
    "createdAt",
    "updatedAt",
  ],
  deviceMonitors: [
    "id",
    "deviceId",
    "name",
    "type",
    "target",
    "port",
    "path",
    "intervalMs",
    "enabled",
    "sortOrder",
    "lastCheckAt",
    "lastResult",
    "lastMessage",
    "lastAlertAt",
    "snmpVersion",
    "snmpCommunity",
    "snmpOid",
    "snmpExpectedValue",
    "portId",
    "snmpIfIndex",
    "snmpMatchMode",
    "snmpCredentialId",
    "ignoreTlsErrors",
  ],
  deviceServices: [
    "id",
    "deviceId",
    "name",
    "serviceType",
    "ipAssignmentId",
    "portId",
    "vlanId",
    "monitorId",
    "url",
    "notes",
    "createdAt",
    "updatedAt",
  ],
  devices: [
    "id",
    "labId",
    "rackId",
    "hostname",
    "displayName",
    "deviceType",
    "manufacturer",
    "model",
    "serial",
    "managementIp",
    "status",
    "startU",
    "heightU",
    "face",
    "tags",
    "notes",
    "lastSeen",
    "placement",
    "parentDeviceId",
    "cpuCores",
    "memoryGb",
    "storageGb",
    "specs",
    "roomId",
    "macAddress",
    "networkMode",
    "snmpCredentialId",
    "rackSlot",
    "ignoreDuplicateMac",
  ],
  dhcpScopes: [
    "id",
    "subnetId",
    "name",
    "startIp",
    "endIp",
    "gateway",
    "dnsServers",
    "description",
  ],
  discoveredDevices: [
    "id",
    "labId",
    "ipAddress",
    "hostname",
    "displayName",
    "deviceType",
    "placement",
    "source",
    "status",
    "notes",
    "importedDeviceId",
    "lastSeen",
    "lastScannedAt",
    "macAddress",
    "vendor",
    "technicalRole",
    "technicalReason",
    "placementHint",
  ],
  discoveryScanSchedules: [
    "id",
    "labId",
    "name",
    "cidr",
    "intervalMs",
    "enabled",
    "lastRunAt",
    "lastResult",
    "lastMessage",
    "createdAt",
    "updatedAt",
  ],
  dockerContainerLinks: [
    "deviceId",
    "sourceId",
    "containerId",
    "containerName",
    "image",
    "state",
    "status",
    "lastSyncedAt",
    "createdAt",
    "updatedAt",
  ],
  dockerImportSources: [
    "id",
    "labId",
    "name",
    "endpoint",
    "tokenEnc",
    "lastSyncAt",
    "lastSyncStatus",
    "lastSyncMessage",
    "createdAt",
    "updatedAt",
    "enabled",
    "verifyTls",
  ],
  integrationConnections: [
    "id",
    "labId",
    "provider",
    "name",
    "baseUrl",
    "authKind",
    "authId",
    "authSecretEnc",
    "siteRef",
    "verifyTls",
    "enabled",
    "syncVlans",
    "syncSubnets",
    "syncDhcp",
    "lastStatus",
    "lastCheckedAt",
    "lastError",
    "lastSummary",
    "createdAt",
    "updatedAt",
    "autoSyncEnabled",
    "autoSyncMode",
    "autoSyncCron",
    "autoSyncLabIds",
    "autoSyncFailureCount",
    "autoSyncPausedUntil",
    "lastAutoSyncAt",
    "lastAutoSyncStatus",
    "lastAutoSyncMessage",
    "scopeRefs",
    "syncDevices",
    "syncWifi",
    "syncSwitches",
    "syncGateways",
    "syncAccessPoints",
    "syncHosts",
    "syncGuests",
  ],
  integrationSyncSchedules: [
    "id",
    "connectionId",
    "name",
    "enabled",
    "mode",
    "cron",
    "labIds",
    "failureCount",
    "pausedUntil",
    "lastRunAt",
    "lastRunStatus",
    "lastRunMessage",
    "createdAt",
    "updatedAt",
  ],
  documentationDeviceLinks: [
    "id",
    "documentationPageId",
    "deviceId",
    "createdAt",
  ],
  documentationPages: [
    "id",
    "labId",
    "title",
    "content",
    "createdAt",
    "updatedAt",
  ],
  driveBayTemplates: [
    "id",
    "name",
    "description",
    "deviceTypes",
    "sections",
    "createdAt",
    "updatedAt",
  ],
  driveSlots: [
    "id",
    "deviceId",
    "name",
    "sectionName",
    "sectionOrder",
    "position",
    "slotType",
    "face",
    "layout",
    "columns",
    "driveId",
    "createdAt",
    "updatedAt",
  ],
  ipAssignments: [
    "id",
    "subnetId",
    "ipAddress",
    "assignmentType",
    "deviceId",
    "portId",
    "vmId",
    "containerId",
    "hostname",
    "description",
    "allocationMode",
    "dhcpScopeId",
  ],
  ipZones: [
    "id",
    "subnetId",
    "kind",
    "startIp",
    "endIp",
    "description",
  ],
  labs: ["id", "name", "description", "location"],
  oidcIdentities: [
    "issuer",
    "subject",
    "userId",
    "email",
    "displayName",
    "createdAt",
    "updatedAt",
  ],
  portLinks: [
    "id",
    "fromPortId",
    "toPortId",
    "cableType",
    "cableLength",
    "color",
    "notes",
  ],
  portTemplates: [
    "id",
    "name",
    "description",
    "deviceTypes",
    "ports",
    "createdAt",
    "updatedAt",
  ],
  ports: [
    "id",
    "deviceId",
    "name",
    "position",
    "kind",
    "speed",
    "linkState",
    "vlanId",
    "description",
    "face",
    "mode",
    "allowedVlanIds",
    "virtualSwitchId",
    "snmpIfIndex",
    "macAddress",
    "portRole",
    "aggregatePortId",
  ],
  racks: [
    "id",
    "labId",
    "name",
    "totalU",
    "description",
    "location",
    "notes",
    "roomId",
  ],
  referenceImages: [
    "id",
    "labId",
    "entityType",
    "entityId",
    "label",
    "fileName",
    "mimeType",
    "dataUrl",
    "face",
    "notes",
    "createdAt",
    "updatedAt",
  ],
  rooms: ["id", "labId", "name", "description", "location", "notes"],
  schemaVersion: ["id", "version", "updatedAt"],
  snmpCredentials: [
    "id",
    "labId",
    "name",
    "version",
    "communityEnc",
    "v3User",
    "v3AuthProto",
    "v3AuthPassEnc",
    "v3PrivProto",
    "v3PrivPassEnc",
    "v3Context",
    "createdAt",
    "updatedAt",
  ],
  snmpSyncSchedules: [
    "id",
    "labId",
    "deviceId",
    "profileId",
    "policy",
    "intervalMs",
    "enabled",
    "lastRunAt",
    "lastResult",
    "lastMessage",
    "createdAt",
    "updatedAt",
  ],
  snmpTrapLog: [
    "id",
    "labId",
    "deviceId",
    "sourceIp",
    "trapOid",
    "ifIndex",
    "varbindsJson",
    "resultAction",
    "message",
    "receivedAt",
  ],
  snmpTrapSources: [
    "id",
    "labId",
    "deviceId",
    "sourceIp",
    "community",
    "credentialId",
    "lastTrapAt",
  ],
  storageDrives: [
    "id",
    "labId",
    "manufacturer",
    "model",
    "serial",
    "capacityGb",
    "interface",
    "formFactor",
    "notes",
    "createdAt",
    "updatedAt",
  ],
  storagePoolDrives: ["poolId", "driveId", "createdAt"],
  storagePools: [
    "id",
    "deviceId",
    "name",
    "poolType",
    "usableCapacityGb",
    "status",
    "notes",
    "createdAt",
    "updatedAt",
  ],
  subnets: [
    "id",
    "labId",
    "cidr",
    "name",
    "description",
    "vlanId",
    "gateway",
    "dnsServers",
  ],
  userLabAccess: ["userId", "labId", "role"],
  users: [
    "id",
    "username",
    "displayName",
    "passwordHash",
    "role",
    "disabled",
    "createdAt",
    "lastLoginAt",
  ],
  userSessions: ["id", "userId", "tokenHash", "createdAt", "expiresAt"],
  virtualSwitches: [
    "id",
    "hostDeviceId",
    "name",
    "notes",
    "kind",
    "membersShareHostIp",
  ],
  vlanRanges: [
    "id",
    "labId",
    "name",
    "startVlan",
    "endVlan",
    "purpose",
    "color",
  ],
  vlans: ["id", "labId", "vlanId", "name", "description", "color"],
  wifiAccessPoints: [
    "deviceId",
    "controllerId",
    "location",
    "firmwareVersion",
    "notes",
  ],
  wifiClientAssociations: [
    "clientDeviceId",
    "apDeviceId",
    "radioId",
    "ssidId",
    "band",
    "channel",
    "signalDbm",
    "lastSeen",
    "lastRoamAt",
    "notes",
  ],
  wifiControllers: [
    "id",
    "labId",
    "deviceId",
    "name",
    "vendor",
    "model",
    "managementIp",
    "notes",
  ],
  wifiRadioSsids: ["radioId", "ssidId"],
  wifiRadios: [
    "id",
    "apDeviceId",
    "slotName",
    "band",
    "channel",
    "channelWidth",
    "txPower",
    "notes",
  ],
  wifiSsids: [
    "id",
    "labId",
    "name",
    "purpose",
    "security",
    "hidden",
    "vlanId",
    "color",
  ],
} as const;

export class RackpadSqliteValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RackpadSqliteValidationError";
  }
}

export function validateRackpadSqliteDatabase(
  database: Database.Database,
  label: string,
) {
  const integrity = database.pragma("integrity_check") as Array<{
    integrity_check: string;
  }>;
  if (integrity.length !== 1 || integrity[0].integrity_check !== "ok") {
    throw new RackpadSqliteValidationError(
      `${label} failed SQLite integrity validation.`,
    );
  }

  const schema = database
    .prepare("SELECT version FROM schemaVersion WHERE id = 1")
    .get() as { version: number } | undefined;
  if (
    !schema ||
    !Number.isInteger(schema.version) ||
    schema.version !== CURRENT_SCHEMA_VERSION
  ) {
    throw new RackpadSqliteValidationError(
      `${label} schema is not supported by this Rackpad version.`,
    );
  }

  const missingSchema: string[] = [];
  for (const [table, requiredColumns] of Object.entries(
    CURRENT_RACKPAD_SCHEMA_COLUMNS,
  )) {
    const columns = new Set(
      (
        database.prepare(`PRAGMA table_info(${table})`).all() as Array<{
          name: string;
        }>
      ).map((column) => column.name),
    );
    if (columns.size === 0) {
      missingSchema.push(table);
      continue;
    }
    for (const column of requiredColumns) {
      if (!columns.has(column)) missingSchema.push(`${table}.${column}`);
    }
  }
  if (missingSchema.length > 0) {
    throw new RackpadSqliteValidationError(
      `${label} is missing required Rackpad schema: ${missingSchema.join(", ")}.`,
    );
  }

  const foreignKeyFailures = database.pragma("foreign_key_check") as unknown[];
  if (foreignKeyFailures.length > 0) {
    throw new RackpadSqliteValidationError(
      `${label} failed foreign-key validation.`,
    );
  }

  return schema.version;
}
